sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t xli68/dod-web -f ./web/Dockerfile.dev ./web

script:
  - docker run -e CI=true xli68/dod-web npm test -- --coverage

after_success:
  - docker build -t xli68/prod-dod-web ./web
  - docker build -t xli68/prod-dod-spb ./backend
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push xli68/prod-dod-web
  - docker push xli68/prod-dod-spb