version: "3.7"
services:
  backer-server:
    image: xli68/dog_of_the_dow:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      spring.datasource.username: shihao
      spring.datasource.password: shihao
      spring.datasource.url: jdbc:mysql://localhost:3306/dog_of_the_dow_app?serverTimezone=UTC
      spring.jpa.hibernate.ddl-auto: update
      tokenSecret: jf9i4jgu83nfl0sshlxn
      server.servlet.context-path: /mobile-app-ws
      server.port: 8080

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dog_of_the_dow_app
      MYSQL_USER: shihao
      MYSQL_PASSWORD: shihao
    ports:
      - "3306:3306"

