name: CI-Pipeline

on:
  push:
     branches:
      - xianan
      - shihao
  pull_request:
    branches:
      - test

jobs:
  Client-CI:
    name: Client-CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build, tag, and test image
        run: |
          docker build -t xli68/web:latest ./web
  
  Server-CI:
    name: Server-CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, tag, and test image
        run: |
          sh ./backend/mysql.sh
          docker container ls
          docker build -t xli68/backend:latest ./backend

  Mobile-CI:
    name: Mobile-CI
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          cd mobile
          npm install
      - name: Run tests
        run: |
          cd mobile
          npm test -- -u
