name: CI-Pipeline

on:
  push:
     branches:
      - xianan
      - shihao
  pull_request:
    branches:
      - test

jobs:
  Client-CI:
    name: Client-CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build, tag, and test image
        run: |
          docker build -t xli68/web:latest ./web
  
  Server-CI:
    name: Server-CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
         java-version: 1.8
      - name: Build with Maven
        run: |
           cd backend/
           sh mysql.sh
           mvn install
           mvn test
           mvn package

      - name: Build, tag, and test image
        run: | 
          docker build -t xli68/backend:latest ./backend

  Mobile-CI:
    name: Mobile-CI
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          cd mobile
          npm install
      - name: Run tests
        run: |
          cd mobile
          npm test -- -u
