name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "dog-of-the-dow-bucket"
  EB_APPLICATION_NAME       : "dog-of-the-dow-app"
  EB_ENVIRONMENT_NAME       : "DogOfTheDowApp-env"
  DEPLOY_PACKAGE_NAME       : "dog-of-the-dow-app-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-1"
  
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - xianan

jobs:
  my_ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repository
        uses: actions/checkout@v1
        
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}
        
      - name: Copy our Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
         
      - name: Print nice message on completion of CI Pipeline
        run : echo "CI Pipeline part finished successfully"
